import fs from 'node:fs/promises';
import {identity,projects} from '../content.mjs';
const icons=Object.fromEntries(await Promise.all(['arrow-up-right','arrow-down','arrow-left','x'].map(async name=>[name,(await fs.readFile(`assets/icons/lucide/${name}.svg`,'utf8')).replace('<svg','<svg class="icon" aria-hidden="true" focusable="false"')])));
const icon=name=>icons[name];
const contact=JSON.parse(await fs.readFile('contact.config.json','utf8'));
const assets=JSON.parse(await fs.readFile('assets/portfolio/manifest.json','utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const img=(name,alt,{eager=false,sizes='(max-width: 540px) 100vw, 92vw'}={})=>{
 const m=assets.find(a=>a.name===name);if(!m)throw new Error('Missing image: '+name);
 const widths=[640,1280,1920].filter((w,i,a)=>i===0||Math.min(w,m.width)!==Math.min(a[i-1],m.width));
 const srcset=widths.map(w=>`/assets/${name}-${w}.webp ${Math.min(w,m.width)}w`).join(', ');
 return `<img src="/assets/${name}-1280.webp" srcset="${srcset}" sizes="${sizes}" width="${m.width}" height="${m.height}" alt="${esc(alt)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
};
const caption=(a,b='')=>`<figcaption class="caption"><span>${a}</span>${b?`<span>${b}</span>`:''}</figcaption>`;
const figure=(name,alt,label,cls='')=>`<figure class="${cls}"><div><button data-enlarge="/assets/${name}-1920.webp" aria-label="Enlarge: ${esc(alt)}">${img(name,alt)}<span class="zoom-label">Enlarge image</span></button></div>${caption(label)}</figure>`;
const full=(name,alt,label,cls='')=>`<div class="wrap image-block">${figure(name,alt,label,`full-image ${cls}`)}</div>`;
const pair=(items,cls='')=>`<div class="wrap image-block"><div class="image-grid ${cls}">${items.map(i=>figure(...i)).join('')}</div></div>`;
const diagram=(name,alt,label)=>`<div class="wrap image-block"><figure><div class="diagram"><button data-enlarge="/assets/${name}.svg" aria-label="Enlarge: ${esc(alt)}"><img src="/assets/${name}.svg" alt="${esc(alt)}" width="1600" height="850" loading="lazy"></button></div>${caption(label,'Composition study · not to scale')}</figure></div>`;
const story=(s)=>`<section class="wrap story"><div class="story-grid"><div class="eyebrow">${s.label}</div><div><h2>${s.title}</h2><p>${s.text}</p></div></div></section>`;
const cards=()=>`<div class="work-grid">${projects.map(p=>`<a class="project-card ${p.slug}" href="/work/${p.slug}/"><div class="visual">${img(p.cover,p.alt,{sizes:p.number==='01'?'92vw':'(max-width: 540px) 90vw, 45vw',eager:p.number==='01'})}<span class="card-arrow" aria-hidden="true">${icon('arrow-up-right')}</span></div><div class="card-caption"><div><h3>${p.title}</h3><p>${p.category}</p></div><span class="card-number">${p.number}</span></div></a>`).join('')}</div>`;
const footer=()=>`<footer class="wrap"><a class="contact-band" href="/contact/"><div><p class="eyebrow">Have a project in mind?</p><h2>Let’s make<br>it visible.</h2></div><span class="big-arrow" aria-hidden="true">${icon('arrow-up-right')}</span></a><div class="site-footer"><span>© ${new Date().getFullYear()} Yemisi Soneye</span><span>Visual identities, environments & experiences.</span></div></footer>`;
const shell=(title,description,body,current='',extra='')=>`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f4f2ed"><title>${esc(title)} — Yemisi Soneye</title><meta property="og:title" content="${esc(title)} — Yemisi Soneye"><meta property="og:description" content="${esc(description)}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header wrap"><a href="/" class="brand" aria-label="Yemisi Soneye, home">Yemisi Soneye<span aria-hidden="true"></span></a><nav aria-label="Main navigation">${['Work','About','Contact'].map(n=>`<a href="/${n.toLowerCase()}/" ${current===n?'aria-current="page"':''}>${n}</a>`).join('')}</nav></header><main id="main">${body}</main>${extra==='nocta'?`<footer class="wrap"><div class="site-footer"><span>© ${new Date().getFullYear()} Yemisi Soneye</span><a href="/work/">Explore the work ${icon('arrow-up-right')}</a></div></footer>`:footer()}<dialog class="lightbox" aria-label="Enlarged project image"><button aria-label="Close enlarged image">${icon('x')}</button><img alt=""></dialog><script src="/site.js" defer></script></body></html>`;
const home=`<section class="home-intro wrap"><p class="eyebrow home-name">Visual & Experiential Designer</p><div class="intro-line"><h1>Visual identities.<br><em>Spatial experiences.</em></h1></div><div class="hero-bottom"><p>Design that connects the image<br>with the experience.</p><a class="text-link" href="#selected-work">Explore selected work <span aria-hidden="true">${icon('arrow-down')}</span></a></div></section><section class="wrap" id="selected-work"><div class="section-line"><h2>Selected work</h2><span class="eyebrow">Graphics / Environments / Experiences</span></div>${cards()}</section><section class="wrap"><div class="home-about"><p class="eyebrow">Across disciplines.<br>Connected by design.</p><div><h2>From a printed page to a space people move through.</h2><div class="capabilities">${identity.capabilities.map(c=>`<span>${c}</span>`).join('')}</div><a class="text-link" href="/about/">About Yemisi <span aria-hidden="true">${icon('arrow-up-right')}</span></a></div></div></section>`;
const caseBody=p=>{
 const s=p.sections;
 if(p.slug==='logos-and-heart')return story(s[0])+pair([
 ['logos-panel','Black, yellow and red panel-session announcement for Logos and heART.','Panel session / event communication'],
 ['logos-campaign','Logos and heART performance announcement with bold Artmosphere typography.','Performance / campaign application']],'prints')+story(s[1])+`<div class="wrap image-block"><figure class="print-spread">${['logos-invitation','logos-vision','logos-programme'].map((n,i)=>`<button data-enlarge="/assets/${n}-1920.webp" aria-label="Enlarge editorial page ${i+1}">${img(n,['Yellow invitation page','Exhibition vision page with colourful painted edges','Programme page combining editorial text and artwork'][i])}</button>`).join('')}</figure>${caption('Editorial sequence / invitation, exhibition story and programme')}</div>`+full('logos-print','Flat artwork for a folded exhibition leaflet, with illustrated panels and exhibition copy.','Exhibition leaflet / graphic layout','folio-print')+story(s[2])+full('logos-wayfinding','Large red and yellow welcome graphic with exhibition identity and illustrated VR visitor.','Large-format welcome graphic / live installation','wide')+diagram('logos-entrance-system','Frontal composition of mirrored panels, coloured apertures, pink stepped profile and yellow identity wall.','Entrance system / form, framing and colour')+pair([
 ['logos-display','Visitor looking at paintings mounted on orange exhibition panels.','Display system / artwork in context'],
 ['logos-installation','Close view of a person installing artwork on an orange panel and its diagonal brace.','Installation detail / the physical frame']],'portrait')+story(s[3])+pair([
 ['logos-window','The yellow identity wall framed through a blue rectangular opening.','Aperture / a view through the environment'],
 ['logos-circle','Yellow exhibition wordmark seen through a circular red aperture.','Colour / a repeated framing device']])+full('logos-auditorium','Exhibition auditorium with red seating, white lounge chairs and branded rear-wall graphics.','Live environment / the exhibition auditorium','wide');
 if(p.slug==='singlz-summit')return story(s[0])+`<div class="wrap image-block"><div class="graphic-study"><div>${img('singlz-campaign','Official Singlz Summit 2024 campaign poster with a red fingerprint, figurative silhouettes and bold orange typography.')}<p class="layout-note">2024 / Campaign communication</p></div><div><h3>Colour, imagery<br>and a circular frame.</h3><div class="circles" aria-hidden="true">${['#c196f7','#ef80c5','#f3e978','#96e2ee','#77d855','#6575ed'].map(c=>`<span style="background:${c}"></span>`).join('')}</div><p>The campaign places bold typography alongside a symbolic illustrated world. On stage, the image-making expands into a family of colourful landscapes, each held within a circular frame.</p></div></div></div>`+story(s[1])+full('singlz-presentation','Clean front-facing presentation of the circular stage, preserving the layout and colour relationships of the completed environment.','Stage composition / presentation view','stage-art')+story(s[2])+full('singlz-panel','Five seated speakers framed by the circular pink, yellow and blue scenic system.','Singlz Summit 2024 / panel conversation','stage-art')+pair([
 ['singlz-social','Social event photograph with a yellow prayer border surrounding the pink scenic circle.','Event communication / the stage in a social frame'],
 ['singlz-live',p.alt,'Live performance / the same visual system']],'portrait');
 if(p.slug==='nlwc')return story(s[0])+full('nlwc-front','Frontal photograph of the NLWC stage showing blue vertical panels over illuminated coral scenery.','Live environment / front view','stage-art')+`<div class="dark-section">${story(s[1])}${diagram('nlwc-stage-system','Seven blue vertical panels arranged over layered warm scenic contours.','Stage language / vertical rhythm and layered contours')}</div>`+story(s[2])+pair([
 ['nlwc-angle','Angled view showing layered mountain forms and a speaker in front.','Alternate view / scenic depth'],
 ['nlwc-wide',p.alt,'Audience view / the full live setting']],'landscape');
 if(p.slug==='emmy-homes-realty')return story(s[0])+pair([
 ['emmy-fairmont','Fairmont apartment campaign, with building rendering, pricing table and blue brand background.','Fairmont / property information'],
 ['emmy-ajaomews','Ajaomews campaign showing a white residential building with blue and gold typography.','Ajaomews / property launch']],'prints');
 if(p.slug==='egfm')return story(s[0])+`<div class="dark-section">${story(s[1])}${diagram('egfm-stage-system','A simplified front composition showing the Who is Like God title and four vertical colour fields on a dark background.','Stage system / graphic composition')}</div>`+story(s[2])+full('egfm-wide',p.alt,'EGFM / live environment','stage-art');
 return '';
};
await fs.mkdir('dist/assets',{recursive:true});
await fs.copyFile('assets/icons/lucide/LICENSE','dist/assets/lucide-LICENSE.txt');
for(const f of await fs.readdir('assets/portfolio'))if(f.endsWith('.webp'))await fs.copyFile('assets/portfolio/'+f,'dist/assets/'+f);
for(const f of await fs.readdir('assets/reconstructed'))if(f.endsWith('.svg'))await fs.copyFile('assets/reconstructed/'+f,'dist/assets/'+f);
for(const f of ['styles.css','site.js'])await fs.copyFile(f,'dist/'+f);
await fs.writeFile('dist/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#20221f"/><text x="32" y="43" text-anchor="middle" font-family="Georgia,serif" font-size="39" fill="#f4f2ed">y</text><circle cx="49" cy="17" r="4" fill="#c74b31"/></svg>');
const write=async(route,html)=>{await fs.mkdir('dist/'+route,{recursive:true});await fs.writeFile('dist/'+route+'index.html',html)};
await write('',shell(identity.role,identity.descriptor,home));
await write('work/',shell('Selected work','Selected visual identities, exhibition experiences, stage environments and campaigns by Yemisi Soneye.',`<section class="wrap page-intro"><p class="eyebrow">Portfolio / ${String(projects.length).padStart(2,'0')} projects</p><h1>Selected work.</h1><p class="deck">Visual systems that move across<br>print, image and space.</p></section><section class="wrap work-index">${cards()}</section>`,'Work'));
for(let i=0;i<projects.length;i++){
 const p=projects[i],next=projects[(i+1)%projects.length];
 const body=`<header class="case-head wrap"><a class="back-link" href="/work/">${icon('arrow-left')} <span>All projects</span></a><div class="case-title-row"><h1>${p.title}</h1><p class="eyebrow">${p.category}${p.year?'<br>'+p.year:''}</p></div></header><figure class="case-hero ${p.slug}">${img(p.cover,p.alt,{eager:true})}</figure><section class="project-intro wrap"><div><p class="eyebrow">Disciplines</p><ul class="disciplines">${p.disciplines.map(d=>`<li>${d}</li>`).join('')}</ul></div><div><h2>${p.intro}</h2><p>${p.description}</p></div></section>${caseBody(p)}<div class="wrap"><section class="next-project"><p class="eyebrow">Next project / ${next.number}</p><a href="/work/${next.slug}/">${next.title}<span aria-hidden="true">${icon('arrow-up-right')}</span></a></section></div>`;
 await write(`work/${p.slug}/`,shell(p.title,p.description,body,'Work'));
}
await write('about/',shell('About',identity.biography,`<section class="wrap page-intro"><p class="eyebrow">About / the practice</p><h1>Yemisi Soneye.</h1><p class="deck">Visual & Experiential Designer</p></section><section class="wrap about-layout"><div><p class="eyebrow">Capabilities</p><ul class="cap-list">${identity.capabilities.map(c=>`<li>${c}</li>`).join('')}</ul></div><div><p class="bio">${identity.biography}</p><p class="bio" style="margin-top:30px">A connected approach to the graphic, the spatial and the moments in between.</p><a href="/work/" class="text-link" style="margin-top:35px">Explore the work <span aria-hidden="true">${icon('arrow-up-right')}</span></a></div></section><figure class="about-image wrap">${img('logos-wayfinding','Environmental welcome graphics at Logos and heART, an example of the practice’s work across image and space.')}</figure>`,'About'));
await write('contact/',shell('Contact','Project enquiries for Yemisi Soneye, Visual & Experiential Designer.',`<section class="wrap contact-page"><div class="page-intro"><p class="eyebrow">Contact / project enquiries</p><h1>Let’s make<br>it visible.</h1></div><div class="contact-copy"><p>For visual identities, campaigns, exhibitions and live environments.</p><p>Get in touch to discuss your project.</p>${contact.email?`<a class="text-link" href="mailto:${esc(contact.email)}">${esc(contact.email)} <span aria-hidden="true">${icon('arrow-up-right')}</span></a>`:'<p>Please reply to the person who shared this portfolio to get in touch.</p>'}${contact.phone?`<p><a href="tel:${esc(contact.phone.replace(/\s/g,''))}">${esc(contact.phone)}</a></p>`:''}${contact.profileUrl?`<p><a href="${esc(contact.profileUrl)}">${esc(contact.profileLabel||'Professional profile')} ${icon('arrow-up-right')}</a></p>`:''}</div></section>`,'Contact','nocta'));
const copy=`# Yemisi Soneye — Portfolio copy\n\nEdit content.mjs to update the website, then run npm run build. Contact details live in contact.config.json. This document collects final copy for easy editorial review.\n\n## Home\n\n${identity.name}\n\n${identity.role}\n\nVisual identities. Spatial experiences.\n\nDesign that connects the image with the experience.\n\nSelected work\n\nGraphics / Environments / Experiences\n\nAcross disciplines. Connected by design.\n\nFrom a printed page to a space people move through.\n\n${identity.capabilities.join(' / ')}\n\n## About\n\n${identity.biography}\n\nA connected approach to the graphic, the spatial and the moments in between.\n\n## Contact\n\nLet’s make it visible.\n\nFor visual identities, campaigns, exhibitions and live environments. Get in touch to discuss your project.\n\n${contact.email||'Email pending'}\n\n`+projects.map(p=>`## ${p.number} — ${p.title}\n\n${p.category}${p.year?' / '+p.year:''}\n\nDisciplines: ${p.disciplines.join(', ')}\n\n### ${p.intro}\n\n${p.description}\n\n${p.sections.map(s=>`### ${s.label} — ${s.title}\n\n${s.text}`).join('\n\n')}`).join('\n\n');
const routes=['','work/','about/','contact/',...projects.map(p=>'work/'+p.slug+'/')];
let allCopy='# Yemisi Soneye — Complete portfolio copy\n\nEditable editorial reference. Website copy is maintained in content.mjs and scripts/build.mjs; contact details are in contact.config.json. Rebuilding refreshes this document.\n\n';
for(const route of routes){
 const html=await fs.readFile('dist/'+route+'index.html','utf8');
 const main=html.match(/<main id="main">([\s\S]*?)<\/main>/)[1];
 const text=main.replace(/<span class="zoom-label">[\s\S]*?<\/span>/g,'').replace(/<(?:\/p|\/h[1-6]|\/li|\/figcaption|\/section|br)[^>]*>/g,'\n\n').replace(/<[^>]*>/g,' ').replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').replaceAll('&amp;','&').replaceAll('&quot;','"').trim();
 allCopy+='## '+(route||'Home')+'\n\n'+text+'\n\n';
}
allCopy+='## Shared footer\n\nHave a project in mind?\n\nLet’s make it visible.\n\n© '+new Date().getFullYear()+' Yemisi Soneye\n\nVisual identities, environments & experiences.\n';
await fs.writeFile('CONTENT.md',allCopy);
console.log(`Built ${projects.length+4} static pages. Public output: dist/`);
